name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    
jobs:

    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 20
    
        - name: Install Dependencies
          run: npm install

        - name: Cache NodeJS Dependancies
          uses: actions/cache@v2
          with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    
        - name: Unit Testing
          run: npm test
          id: nodejs-unti-test-step
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml
          if: always() # Always upload the test result

    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Cache NodeJS Dependancies
          uses: actions/cache@v2
          with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    
        - name: Install Dependencies
          run: npm install
    
        - name: Check Code Coverage
          run: npm run coverage
          continue-on-error: true
          
        - name: Archive Code Coverage
          uses: actions/upload-artifact@v3
          with:
            name: Code-Coverage-Result
            path: coverage
            retention-days: 5
            
    docker:
        permissions:
          contents: read
          packages: write

        name: DockerHub login
        needs: [unit-testing, code-coverage]
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Login to GHCR
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build Docker Image
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./Dockerfile
            push: false
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

        - name: Docket test
          run: |
            docker images
            docker run -d -p 3000:3000 --name solar-system-app \
                -e MONGO_URI=${{ env.MONGO_URI }} \
                -e MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
                -e MONGO_PASSWORD=${{ env.MONGO_PASSWORD }} \
               ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

            export IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
            echo "IP Address: $IP"

        - name: Push Images 
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
              ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}

          